<?php
const LEAD_STATUE = ['Cooking','Dead Deal','Approved','Sent','Not Sent'];
const JOB_TYPE = [
    'Tile Roofs to Tile Roofs',
    'Tile & Flat to Tile & Flat',
    'Shingle Roofs to Shingle Roofs',
    'Shingle & Flat to Shingle Roofs',
    'Metal Roofs',
    'Flat Roofs',
    'Flat Roofs with ISO',
    'Commercial Flat Roofs',
];
const ROLE = ['Admin','Sales Representative','Sub Constructor'];
const PRODUCT_TYPE = ['Material','Labor','Trash','Permit'];
const PRODUCT_CATEGORY = ['Tile','Metal','Shingle','Flat'];

const CITY_LIST = [
    'Aventura',
    'Bal Harbour',
    'Bal Harbour Islands',
    'Biscayne Park',
    'Cooper City',
    'Coral Gables',
    'Coral Springs',
    'Cutler Bay',
    'Davie',
    'Doral',
    'El Portal',
    'Florida City',
    'Fort Lauderdale',
    'Golden Beach',
    'Hialeah',
    'Hialeah Gardens',
    'Hollywood',
    'Homestead',
    'Indian Creek',
    'Key Biscayne',
    'Medley',
    'Miami',
    'Miami Beach',
    'Miami Gardens',
    'Miami Lakes',
    'Miami Shores',
    'Miami Springs',
    'Miramar',
    'North Bay Village',
    'North Miami',
    'North Miami Beach',
    'Opa-locka',
    'Palmetto Bay',
    'Pembroke Pines',
    'Pinecrest',
    'Plantation',
    'Pompano Beach',
    'South Miami',
    'Sunny Isles Beach',
    'Sunrise',
    'Surfside',
    'Sweetwater',
    'Unincorporated Miami-Dade County',
    'Virginia Gardens',
    'West Miami',
    'Weston'
];
